In [0]:
import torch

In [2]:
x = torch.tensor([5,3])
y = torch.tensor([2,1])
print(x*y)

tensor([10,  3])


In [0]:
x = torch.zeros([2,5])


In [4]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [0]:
 y =torch.rand(2,5,1)

In [25]:
y

tensor([[[0.5280],
         [0.2962],
         [0.2162],
         [0.4666],
         [0.3062]],

        [[0.7894],
         [0.5884],
         [0.1912],
         [0.6918],
         [0.9545]]])

In [26]:
y.ndim

3

In [27]:
#same like ravel
y.view(1,10)

tensor([[0.5280, 0.2962, 0.2162, 0.4666, 0.3062, 0.7894, 0.5884, 0.1912, 0.6918,
         0.9545]])

In [28]:
y

tensor([[[0.5280],
         [0.2962],
         [0.2162],
         [0.4666],
         [0.3062]],

        [[0.7894],
         [0.5884],
         [0.1912],
         [0.6918],
         [0.9545]]])

In [29]:
y=y.view(1,10)
y

tensor([[0.5280, 0.2962, 0.2162, 0.4666, 0.3062, 0.7894, 0.5884, 0.1912, 0.6918,
         0.9545]])